import type { Metadata } from "next";
import Provider from "./providers";
import "./globals.css";
import AuthProvider from "./AuthProvider";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";
import { ToastContainer, toast } from "react-toastify";

export const metadata: Metadata = {
  title: "Diploma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastContainer />
          {/* <TokenSync /> */}
          <Provider>
            {/* <NavBar /> */}
            {children}
            {/* <Footer/> */}
          </Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
